CREATE TABLE `markets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`polymarket_id` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`symbol` varchar(10) NOT NULL,
	`dataset` text,
	`condition_id` text,
	`outcomes` json NOT NULL,
	`outcome_prices` json,
	`resolved_outcome` text,
	`end_date` timestamp,
	`start_date` timestamp,
	`start_date_iso` text,
	`uma_resolution_status` text,
	`clob_token_ids` json,
	`active` boolean NOT NULL DEFAULT false,
	`closed` boolean NOT NULL DEFAULT false,
	`volume` decimal,
	`question` text NOT NULL,
	`raw_json` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `markets_id` PRIMARY KEY(`id`),
	CONSTRAINT `markets_polymarket_id_unique` UNIQUE(`polymarket_id`),
	CONSTRAINT `markets_slug_unique` UNIQUE(`slug`)
);
