/**
 * Golden generator (60 §7.1 GF-1/GF-2, §7.2 row "ts-compat fee (4 dp,
 * 0.0001 floor)"): evaluates the TS oracle `computePolymarketTakerFee`
 * (`src/trading/fees.ts:18-42`) at 700 bps over a grid of prices and sizes
 * and writes `fee_expected.txt`, one vector per line:
 * `<price> <size> <tsFeeMicros> [<annotation>]`.
 *
 * The golden keeps the TS value (GF-5). A vector whose exact fee
 * `0.07 × p × (1 − p) × C` lies exactly on a 4-dp half and where the TS
 * float result differs from the exact `HalfAwayFromZero` value is annotated
 * `PE-R3` (60 §3.5); any other difference is annotated `UNEXPECTED`, which
 * the Rust test rejects.
 *
 * Usage: npx tsx native/crates/pmb-engine/src/exec/sim/tests/golden/fee_gen.ts
 */
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { computePolymarketTakerFee } from '../../../../../../../../src/trading/fees.js'

const prices: string[] = []
for (let c = 1; c <= 99; c++) prices.push((c / 100).toFixed(2))
prices.push('0.001', '0.123', '0.505', '0.555', '0.875', '0.999', '0.1234', '0.5001', '0.0005')
const sizes = [
  '0.000001',
  '0.002',
  '0.005',
  '0.01',
  '0.03',
  '0.1',
  '1',
  '2',
  '3.33',
  '5',
  '7',
  '10',
  '10.02',
  '12.345678',
  '13.37',
  '99.99',
  '100',
  '250.5',
  '1000',
  // Exact 4-dp ties that the TS float product rounds down (PE-R3 at p = 0.30).
  '5.5',
  '10.5',
  '13.5',
  '18.5',
  '50.5',
]

const SCALE = 1_000_000n
const micros = (s: string): bigint => {
  const [i, f = ''] = s.split('.')
  return BigInt(i!) * SCALE + BigInt((f + '000000').slice(0, 6))
}

/** Exact fee in 1e-4 USDC units as a rational `num / 1e16`. */
function exactFee(p: bigint, c: bigint): { micros: bigint; tie: boolean } {
  const num = 7n * p * (SCALE - p) * c // fee × 1e4 = num / 1e16
  const den = 10n ** 16n
  const q = num / den
  const r = num % den
  const tie = 2n * r === den
  const units = 2n * r >= den ? q + 1n : q // HalfAwayFromZero (fee ≥ 0)
  return { micros: units * 100n, tie }
}

const lines = [
  '# Generated by fee_gen.ts with the TS oracle src/trading/fees.ts (700 bps).',
  '# <price> <size> <tsFeeMicros> [PE-R3]. Do not edit; regenerate.',
]
for (const p of prices) {
  for (const c of sizes) {
    const ts = computePolymarketTakerFee({ feeRateBps: 700, price: Number(p), size: Number(c) })
    const tsMicros = BigInt(Math.round(ts * 1e6))
    const exact = exactFee(micros(p), micros(c))
    let note = ''
    if (tsMicros !== exact.micros) note = exact.tie ? ' PE-R3' : ' UNEXPECTED'
    lines.push(`${p} ${c} ${tsMicros}${note}`)
  }
}
writeFileSync(path.join(import.meta.dirname, 'fee_expected.txt'), lines.join('\n') + '\n')
