//! ts-compat fee golden (60 §7.2 row "ts-compat fee (4 dp, 0.0001 floor)";
//! 11 §4; 13 §5.1 TC-E7): `golden/fee_expected.txt` holds the TS oracle's
//! fee (`src/trading/fees.ts`, generated by `fee_gen.ts`). Rust must equal
//! it exactly, except on vectors annotated `expected_divergence = "PE-R3"`
//! (60 §3.5, GF-5): there the exact fee lies on a 4-dp half, TS rounds an
//! `f64` product, and Rust must give the spec value (10 R8: one
//! `HalfAwayFromZero` step from the exact value), 1e-4 above the TS value.

use pmb_core::{Price, Qty};

use super::super::fee::Fee700Bps4dp;
use super::dec;

const GOLDEN: &str = include_str!("golden/fee_expected.txt");

/// The spec value computed independently of the fee model: the exact fee
/// `7 × p × (1 − p) × C / 1e16` in 1e-4 USDC units (micros inputs), rounded
/// once `HalfAwayFromZero`, plus whether it was an exact tie.
fn spec_fee(p: i64, c: i64) -> (i64, bool) {
    let num = 7i128 * p as i128 * (1_000_000 - p) as i128 * c as i128;
    let den = 10i128.pow(16);
    let (q, r) = (num / den, num % den);
    let units = if 2 * r >= den { q + 1 } else { q };
    ((units * 100) as i64, 2 * r == den)
}

#[test]
fn ts_compat_fee_matches_the_ts_golden() {
    // spec: 60 §7.2 (ts-compat fee golden, exact; ties annotated PE-R3), 11 §4, 10 R8
    let (mut n, mut ties) = (0, 0);
    for line in GOLDEN.lines().filter(|l| !l.starts_with('#')) {
        let w: Vec<&str> = line.split_whitespace().collect();
        let (p, c) = (dec(w[0]), dec(w[1]));
        let ts: i64 = w[2].parse().expect("ts micros");
        let rust = Fee700Bps4dp::taker_fee(Price::from_micros(p), Qty::from_micros(c)).micros();
        let (spec, tie) = spec_fee(p, c);
        assert_eq!(rust, spec, "{line}: Rust differs from the spec value");
        match w.get(3) {
            None => assert_eq!(rust, ts, "{line}: Rust differs from the TS golden"),
            // expected_divergence = "PE-R3"
            Some(&"PE-R3") => {
                assert!(tie, "{line}: PE-R3 requires an exact 4-dp tie");
                assert_eq!(rust - ts, 100, "{line}: PE-R3 is exactly 1e-4");
                ties += 1;
            }
            Some(other) => panic!("{line}: unclassified divergence {other}"),
        }
        n += 1;
    }
    assert_eq!(n, 108 * 24);
    assert!(ties > 0, "the golden exercises PE-R3");
}

#[test]
fn floor_and_minimum_follow_the_ts_rule() {
    // spec: 10 R8 (4 dp; a result below 0.0001 is 0), 11 §4
    // 0.07 × 0.25 × 0.0014 = 0.0000245 → 0; × 0.0029 = 0.00005075 → 0.0001.
    let half = Price::from_micros(500_000);
    assert_eq!(
        Fee700Bps4dp::taker_fee(half, Qty::from_micros(1_400)).micros(),
        0
    );
    assert_eq!(
        Fee700Bps4dp::taker_fee(half, Qty::from_micros(2_900)).micros(),
        100
    );
}
