// Generated by `npm run native:contract:gen` from native/contract/schema/v1
// (21 §3). Do not edit: change pmb-contract, then regenerate.
// Roots: EngineJob (engineJob.schema.json), EngineResult (engineResult.schema.json), ModelConfig (modelConfig.schema.json), ServeIn (serveIn.schema.json), ServeOut (serveOut.schema.json).

export type AnomalyValue = number | { [key: string]: number }

export interface CacheStats {
  hits: number
  misses: number
}

/**
 * `ModelConfig.execution.cancelBeforeAck` (13 §7.3; realistic, M3b).
 */
export type CancelBeforeAck = 'defer_until_ack' | 'immediate'

/**
 * Capital-aware counters per candidate (21 §10).
 */
export interface CandidateCounters {
  buyNotionalUsdc: string
  key: string
  ordersCanceled: number
  ordersPlaced: number
  /**
   * Keyed by reject reason code (the text before `(`; a closed
   * vocabulary, 21 §17, 10 §10.2).
   */
  ordersRejected: {
    amount_precision?: number
    batch_too_large?: number
    gtd_expireAtMs_too_soon?: number
    gtd_lead_too_short?: number
    gtd_requires_expireAtMs?: number
    insufficient_capital?: number
    insufficient_exchange_balance?: number
    insufficient_inventory?: number
    invalid_price?: number
    invalid_size?: number
    invalid_tick?: number
    kill_switch?: number
    market_closed?: number
    meta_too_large?: number
    missing_assetId?: number
    not_found_after_ambiguous?: number
    notional_below_minimum?: number
    post_only_requires_gtc_or_gtd?: number
    post_only_would_cross?: number
    price_out_of_bounds?: number
    rate_limited?: number
    risk_loss_stop?: number
    risk_max_abs_position?: number
    risk_max_open_orders?: number
    risk_max_order_size?: number
    self_cross?: number
    size_below_minimum?: number
    size_precision?: number
    strategy_halted?: number
    trading_restricted?: number
    unmapped?: number
  }
  peakReservedUsdc: string
  sellNotionalUsdc: string
  strategyTicksSkipped: number
}

/**
 * One candidate's result: `output` iff `status = ok`, `error` iff
 * `status = error` (checked by [`CandidateResult::validate`]).
 */
export interface CandidateResult {
  error?: ErrorInfo
  index: number
  key: string
  /**
   * Hash of this candidate's effective ModelConfig (21 §1.1).
   */
  modelConfigSha256: string
  output?: EngineMarketOutput
  status: ResultStatus
}

/**
 * One candidate (21 §8).
 */
export interface CandidateSpec {
  /**
   * A complete `execution` object replacing the run's, or null (C4).
   */
  execution: ExecutionConfig | null
  index: number
  key: string
  /**
   * Opaque: validated by the strategy's `paramsSchema` (21 §3).
   */
  params: { [key: string]: unknown }
}

/**
 * Per-market capital allowance (12 §9.4).
 */
export interface CapitalConfig {
  startingCapitalUsdc: string
}

/**
 * `captured`: any subset of the 11 keys of 11 §13.4.
 */
export interface CapturedRules {
  acceptingOrdersTimestampMs?: Captured_SafeI64
  feeSchedule?: Captured_FeeSchedule
  feeType?: Captured_FeeType
  feesEnabled?: Captured_boolean
  minOrderAgeS?: Captured_uint32
  minSizeResting?: Captured_Decimal
  negRisk?: Captured_boolean
  secondsDelay?: Captured_uint32
  takerDelayEnabled?: Captured_boolean
  tick?: Captured_Decimal
  version?: Captured_MarketVersion
}

/**
 * One captured value with its provenance (21 §7.1).
 */
export interface Captured_Decimal {
  origin: RulesOrigin
  phase: RulesPhase
  /**
   * `exchange_rules_snapshots.id`, positive.
   */
  snapshotId: number
  value: string
}

/**
 * One captured value with its provenance (21 §7.1).
 */
export interface Captured_FeeSchedule {
  origin: RulesOrigin
  phase: RulesPhase
  /**
   * `exchange_rules_snapshots.id`, positive.
   */
  snapshotId: number
  value: FeeSchedule
}

/**
 * One captured value with its provenance (21 §7.1).
 */
export interface Captured_FeeType {
  origin: RulesOrigin
  phase: RulesPhase
  /**
   * `exchange_rules_snapshots.id`, positive.
   */
  snapshotId: number
  value: FeeType
}

/**
 * One captured value with its provenance (21 §7.1).
 */
export interface Captured_MarketVersion {
  origin: RulesOrigin
  phase: RulesPhase
  /**
   * `exchange_rules_snapshots.id`, positive.
   */
  snapshotId: number
  value: MarketVersion
}

/**
 * One captured value with its provenance (21 §7.1).
 */
export interface Captured_SafeI64 {
  origin: RulesOrigin
  phase: RulesPhase
  /**
   * `exchange_rules_snapshots.id`, positive.
   */
  snapshotId: number
  value: number
}

/**
 * One captured value with its provenance (21 §7.1).
 */
export interface Captured_boolean {
  origin: RulesOrigin
  phase: RulesPhase
  /**
   * `exchange_rules_snapshots.id`, positive.
   */
  snapshotId: number
  value: boolean
}

/**
 * One captured value with its provenance (21 §7.1).
 */
export interface Captured_uint32 {
  origin: RulesOrigin
  phase: RulesPhase
  /**
   * `exchange_rules_snapshots.id`, positive.
   */
  snapshotId: number
  value: number
}

export interface ChainlinkFeed {
  latency: Distribution
  /**
   * 0 disables the gap check; otherwise at least 1,000 (14 §9).
   */
  maxGapMs: number
}

/**
 * `ModelConfig.clock` (12 §4.5). Realistic, M3b.
 */
export interface ClockConfig {
  marketData: MarketDataClock
}

/**
 * TS latency parameters: one delay for every placement and cancel, jitter
 * only when the delay is positive (13 §5.1 `NextRealTick`).
 */
export interface CompatLatency {
  delayMs: number
  jitterMs: number
}

/**
 * `ModelConfig.execution.models.depletion` (13 §7.3).
 */
export type DepletionModel = 'persistent_deficit' | 'reset_on_update' | 'none'

/**
 * Machine-dependent metrics; never compared, never persisted (21 §10).
 */
export interface Diagnostics {
  /**
   * Data-anomaly, rules, engine and attribution counters under their
   * owners' names (15 §8, 10, 11, 12, 13 §7.2); zero counters may be
   * omitted. Values are counts or count-by-reason maps.
   */
  anomalies: { [key: string]: AnomalyValue }
  busyMs: number
  cache: CacheStats
  counters: CandidateCounters[]
  cpuMs: number
  finishedAtMs: number
  inputPath: InputPath
  peakRssBytes: number
  /**
   * Final exchange-time skew (12 §4.4 XT4); null without market events.
   */
  skewMs: number | null
  startedAtMs: number
  thread: number
  wallMs: number
}

/**
 * A latency distribution (13 §7.3).
 */
export type Distribution =
  | {
      kind: 'constant'
      ms: number
    }
  | {
      hiMs: number
      kind: 'uniform'
      loMs: number
    }
  | {
      kind: 'empirical'
      quantilesMs: number[]
    }
  | {
      kind: 'lognormal'
      mu: string
      sigma: string
    }

/**
 * Echo of the request for the shim's assertions (21 §12).
 */
export interface Echo {
  /**
   * 40-hex source commit (20 §3).
   */
  engineCommit: string
  /**
   * Engine crate semver (20 §3).
   */
  engineVersion: string
  jobSchemaVersion: number
  modelConfigSha256: string
  profile: Profile
  /**
   * Copied from `modelConfig.rules` (21 §10).
   */
  rulesTableVersion: string
  seed: number
  /**
   * Copied from `market.rules` (21 §10).
   */
  snapshotParserVersion: number | null
  strategyId: string
}

/**
 * The thread QoS class read back after setting it (16 §10.2); a
 * clamped process can report a class it did not request.
 */
export type EffectiveQos =
  | 'user-interactive'
  | 'user-initiated'
  | 'default'
  | 'utility'
  | 'background'
  | 'unspecified'

export interface EngineJob {
  budget: JobBudget
  jobSchemaVersion: 1
  market: MarketSection
  outputs: JobOutputs
  run: RunSection
}

/**
 * `RunSingleMarketOutput` minus `idx` and `durationMs` (21 §11).
 */
export interface EngineMarketOutput {
  /**
   * 1..32 non-empty strings of at most 512 characters (21 §13).
   */
  coverageReasons?: string[]
  eventsByType: EventsByType
  eventsProcessed: number
  /**
   * Null for the null-stats rows of 21 §13.
   */
  marketStats: EngineMarketStats | null
  skipReason?: SkipReason
  slug: string
}

/**
 * `MarketStats` without `execution` and `recorderV4Capture` (21 §11).
 */
export interface EngineMarketStats {
  avgEntryPriceDown: number | null
  /**
   * BUY VWAP; null iff that outcome has no BUY fill (21 §11).
   */
  avgEntryPriceUp: number | null
  cost: number
  downShares: number
  feesPaid: number
  finalOutcome: Outcome
  /**
   * Opaque strategy meta objects (21 §16).
   */
  intentMeta: Array<{ [key: string]: unknown }>
  marketId: string
  mergableShares: number
  /**
   * |x| < 1e10 (21 §11).
   */
  pnl: number
  /**
   * Object in realistic, null in ts-compat (11 §13.8). Absent only on
   * TS-engine rows, which are not engine output.
   */
  rules: MarketStatsRules | null
  skipReason?: StatsSkipReason
  slug: string
  splitCost: number
  tradeAsMaker: number
  tradeAsTaker: number
  tradeCount: number
  upShares: number
}

export interface EngineResult {
  candidates: CandidateResult[]
  diagnostics: Diagnostics
  /**
   * Null only in a group-level error of a class that can be raised
   * before the job is read ([`ErrorClass::may_precede_job_read`]);
   * `echo` and `market` are null together.
   */
  echo: Echo | null
  /**
   * Present iff `status` is `error`.
   */
  error: ErrorInfo | null
  /**
   * Null together with `echo` (see there).
   */
  market: MarketEcho | null
  outputSchemaVersion: 1
  /**
   * sha256 of the serialized deterministic section (every field except
   * `diagnostics`).
   */
  resultDigest: string
  /**
   * Group-level status.
   */
  status: ResultStatus
}

/**
 * Error classes (20 §4; the only class list).
 */
export type ErrorClass =
  | 'runtime'
  | 'invalid_input'
  | 'data_missing'
  | 'data_defect'
  | 'timeout'
  | 'invalid_output'
  | 'strategy_fault'
  | 'engine_fault'
  | 'killed'
  | 'canceled'

export interface ErrorDetail {
  callback?: string
  fixCommand?: string
  location?: string
  path?: string
  seq?: number
  tsMs?: number
}

/**
 * `ErrorInfo` (21 §10).
 */
export interface ErrorInfo {
  cause: string
  class: ErrorClass
  detail?: ErrorDetail
  /**
   * One line, at most 1,000 characters.
   */
  message: string
}

/**
 * Counted ticks per cause (21 §15). Absent keys are zero. Values are
 * integers >= 0; the engine emits the canonical form, which omits unseen
 * causes as TS does ([`EventsByType::from_counts`]), and accepts an
 * explicit 0 on input as 21 §15 allows.
 */
export interface EventsByType {
  binance_agg_trade?: number
  book?: number
  chainlink_round?: number
  price_change?: number
}

/**
 * `ModelConfig.execution` v1 (13 §7.3).
 */
export interface ExecutionConfig {
  /**
   * M3b.
   */
  cancelBeforeAck?: CancelBeforeAck
  /**
   * Used iff `models.latency = compat` (13 §5.1).
   */
  compatLatency: CompatLatency
  /**
   * M3b.
   */
  failureRates?: FailureRates
  /**
   * Realistic latency components (13 §6.8). M3b.
   */
  latency?: LatencyCalibration
  /**
   * M3b.
   */
  makerQueue?: MakerQueueConfig
  models: ExecutionModels
  /**
   * M3b.
   */
  sellGate?: SellGate
}

/**
 * The six model axes (13 §7.1, §7.3).
 */
export interface ExecutionModels {
  depletion: DepletionModel
  fee: FeeModel
  latency: LatencyModel
  maker: MakerModel
  reports: ReportsModel
  takerDelay: TakerDelayModel
}

/**
 * Failure rates (13 §7.3). M3b.
 */
export interface FailureRates {
  chain: string
  settlement: string
}

/**
 * `ModelConfig.execution.models.fee` (13 §7.3).
 */
export type FeeModel = 'schedule' | 'flat_700bps_4dp'

/**
 * `feeSchedule {rate, exponent, takerOnly}` (11 §13.4).
 */
export interface FeeSchedule {
  /**
   * 0..=4 (11 FE3).
   */
  exponent: number
  rate: string
  takerOnly: boolean
}

/**
 * Gamma `feeType`, `^[a-z0-9_]{1,64}$`; unknown types are accepted here and
 * handled by 11 FE3.
 */
export type FeeType = string

/**
 * Producer-resolved feed availability (14 §6.2).
 */
export interface FeedAvailability {
  /**
   * Null when the strategy did not request price-to-beat.
   */
  priceToBeat: PriceToBeatAvailability | null
}

/**
 * One feed day file (14 §4.1, §5.1).
 */
export interface FeedFile {
  bytes: number
  day: string
  feed: FeedId
  path: string
  symbol: string
}

/**
 * Feed ids of `market.feedFiles` (21 §17).
 */
export type FeedId = 'binance_agg_trades' | 'chainlink_crypto_prices'

export interface FeedLatency {
  latency: Distribution
}

/**
 * `ModelConfig.feeds` (14 §9).
 */
export interface FeedsConfig {
  binance: FeedLatency
  calibrationId: string
  chainlink: ChainlinkFeed
  priceToBeat: FeedLatency
}

export interface FileRef {
  bytes: number
  path: string
  sha256: string
}

export interface GammaPriceToBeat {
  priceToBeat: number | null
  syncedAtMs: number | null
}

/**
 * A candidate inside strategy code for more than 1 s (40 §8.2.3, 41 §8).
 */
export interface InCallback {
  callback: string
  candidateIndex: number
  candidateKey: string
  sinceMs: number
}

/**
 * One in-flight job in `pong`.
 */
export interface InflightJob {
  elapsedMs: number
  eventsProcessed: number
  inCallback: InCallback | null
  jobId: string
}

export interface InputFormat {
  name: string
  version: number
}

/**
 * Native input modes (21 §17). `recorded` and `telonex-paired` are not
 * native modes (20 §5.6).
 */
export type InputMode = 'telonex-delta' | 'recorder-v4' | 'journal'

/**
 * Input path taken by the reader (16 §7.5 NT-5), diagnostics only.
 */
export type InputPath = 'tape' | 'v1'

/**
 * Logical input file (15 I-8).
 */
export interface InputRef {
  bytes: number
  format: InputFormat
  path: string
  /**
   * Required for `recorder-v4` and `journal` inputs (15 §9).
   */
  sha256: string | null
}

/**
 * Non-semantic budget (21 §5.1).
 */
export interface JobBudget {
  threads: number
  wallMs: number
}

/**
 * Non-semantic output paths (21 §5.1, 22).
 */
export interface JobOutputs {
  ledgerPath: string | null
  traceLevel: TraceLevel
  tracePath: string | null
}

/**
 * Journal replay options (15 §9, I-50, I-51).
 */
export interface JournalInput {
  /**
   * Turns the run into a what-if replay that cannot serve as a
   * determinism proof (I-51).
   */
  allowEngineMismatch: boolean
  replay: JournalReplay
}

/**
 * `market.journal.replay` (15 §9, I-50).
 */
export type JournalReplay = 'determinism'

/**
 * Realistic latency calibration (13 §6.8, §7.4). M3b.
 */
export interface LatencyCalibration {
  calibrationId: string
  components: LatencyComponents
}

/**
 * The realistic latency components (13 §7.3).
 */
export interface LatencyComponents {
  ack: Distribution
  cancel: Distribution
  cancelAck: Distribution
  chainMerge: Distribution
  chainSplit: Distribution
  confirmed: Distribution
  failed: Distribution
  fillReport: Distribution
  mined: Distribution
  place: Distribution
}

/**
 * `ModelConfig.execution.models.latency` (13 §7.3).
 */
export type LatencyModel = 'exact' | 'compat'

/**
 * `ModelConfig.execution.models.maker` (13 §7.3).
 */
export type MakerModel = 'queue' | 'trade_through' | 'worst_queue'

/**
 * Maker queue parameters (13 §6.5, §7.3). M3b.
 */
export interface MakerQueueConfig {
  cancelAheadShare: string
  printMatchWindowMs: number
  prints: MakerQueuePrints
}

/**
 * `ModelConfig.execution.makerQueue.prints` (13 §7.3; realistic, M3b).
 */
export type MakerQueuePrints = 'auto' | 'off'

export interface MarketDataClock {
  calibrationId: string
  delay: Distribution
}

export interface MarketEcho {
  /**
   * Market id of the first counted tick; null when there was none.
   */
  conditionId: string | null
  rulesSource: RulesSource
  slug: string
}

/**
 * `market.rules`: captured values only (11 JC1).
 */
export interface MarketRules {
  captured: CapturedRules
  /**
   * RS3 Gamma-vs-CLOB disagreements.
   */
  disagreements: number
  /**
   * Positive; `null` iff `captured` is empty.
   */
  snapshotParserVersion: number | null
}

export interface MarketSection {
  /**
   * `telonex_markets.market_id`, the V4 manifest or the journal header;
   * null when unknown (15 I-18).
   */
  conditionId: string | null
  feedAvailability: FeedAvailability
  feedFiles: FeedFile[]
  /**
   * Tri-state: absent = not requested, null = catalog miss, object =
   * resolved (21 §5.1).
   */
  gammaPriceToBeat?: GammaPriceToBeat | null
  input: InputRef
  /**
   * Required iff `inputMode` is `journal` (15 §9, I-50, I-51).
   */
  journal: JournalInput | null
  outcome: Outcome
  /**
   * Calibration only (15 I-39).
   */
  ownActivity: OwnActivity | null
  /**
   * Required iff `inputMode` is `recorder-v4` (15 §5).
   */
  recorderV4: RecorderV4Input | null
  rules: MarketRules
  slug: string
  tokenIds: TokenIds
  /**
   * Null only for recorder-v4 in ts-compat (21 §5.1).
   */
  window: Window | null
}

/**
 * Per-market rules provenance (11 §13.8). Values of `feeEra`, `feeCurve`,
 * `feeSource` and rule ids come from the run's rule table (11 VR2).
 */
export interface MarketStatsRules {
  feeCurve: string
  feeEra: string
  feeSource: string
  rulesTableVersion: string
  snapshotParserVersion: number | null
  source: RulesSource
  /**
   * Sorted, unique.
   */
  unverifiedRules: string[]
}

/**
 * Market exchange version (11 V1).
 */
export type MarketVersion = 'v1' | 'v2'

/**
 * `ModelConfig.rules.missingSnapshot` (11 §13.4; one value in v1).
 */
export type MissingSnapshot = 'dated_fallback'

/**
 * The complete, producer-resolved model settings of a run (21 §6).
 */
export interface ModelConfig {
  capital: CapitalConfig
  /**
   * Market-data clock (12 §4.5). Realistic only; absent in ts-compat
   * until M3b (D57).
   */
  clock?: ClockConfig
  execution: ExecutionConfig
  feeds: FeedsConfig
  modelConfigVersion: 1
  profile: Profile
  risk: RiskConfig
  rules: RulesConfig
  runner: RunnerConfig
  /**
   * Run seed in `[0, 2^53 - 1]` (10 §6.1 RNG-1).
   */
  seed: number
}

/**
 * Market outcome; also the `tokenIds` keys and `finalOutcome` (21 §17).
 */
export type Outcome = 'UP' | 'DOWN'

/**
 * Own-activity ledger for decontaminated calibration replays (15 I-39).
 */
export interface OwnActivity {
  clock: OwnActivityClock
  ledger: FileRef
  maxPlacementMs: number
  restoreHorizonMs: number
}

export interface OwnActivityClock {
  offsetMs: number
  uncertaintyMs: number
}

/**
 * One `hw.perflevelN` entry (16 §10.1).
 */
export interface PerfLevel {
  name: string
  physicalCpu: number
}

export interface PriceToBeatAvailability {
  /**
   * Required for `unavailable_*` (14 §6.2); one line.
   */
  message?: string
  status: PriceToBeatStatus
}

/**
 * Producer-resolved price-to-beat availability (14 §6.2).
 */
export type PriceToBeatStatus =
  | 'fed'
  | 'absent_pre_series_epoch'
  | 'absent_fresh_market_grace'
  | 'unavailable_pipeline_incomplete'
  | 'unavailable_upstream_hole'

/**
 * Execution profile (21 §17, 13 §7.2).
 */
export type Profile = 'ts-compat' | 'realistic'

/**
 * Requested and effective thread QoS (16 §10.2).
 */
export interface Qos {
  effective: EffectiveQos
  requested: QosClass
}

/**
 * `serve --qos` values (16 §10.2), echoed as `ready.qos.requested`.
 */
export type QosClass = 'user-initiated' | 'default' | 'utility' | 'background'

/**
 * Recorder V4 input (15 §5). `manifest` is opaque here and validated by the
 * V4 manifest schema (21 §3).
 */
export interface RecorderV4Input {
  allowGaps: boolean
  manifest: { [key: string]: unknown }
}

/**
 * `ModelConfig.execution.models.reports` (13 §7.3).
 */
export type ReportsModel = 'settlement' | 'compat'

/**
 * Group-level and candidate-level result status (21 §10).
 */
export type ResultStatus = 'ok' | 'error'

/**
 * `ModelConfig.risk` (12 §8).
 */
export interface RiskConfig {
  maxAbsPosition: string
  maxLossStopUsdc: string
  maxOpenOrders: number
  maxOrderSize: string
}

/**
 * `ModelConfig.rules` (11 §13.4).
 */
export interface RulesConfig {
  missingSnapshot: MissingSnapshot
  rulesTableVersion: string
}

/**
 * Origin of a captured rules value (11 §13.1).
 */
export type RulesOrigin = 'gamma' | 'clob' | 'v4_bootstrap' | 'live_gamma' | 'live_clob'

/**
 * Capture phase relative to the market start (11 §13.1).
 */
export type RulesPhase = 'pre_start' | 'post_start'

/**
 * Rules provenance of a market (11 RS4).
 */
export type RulesSource = 'snapshot' | 'partial' | 'fallback'

/**
 * Run-level section, identical for every market of a submission or group.
 */
export interface RunSection {
  candidates: CandidateSpec[]
  inputMode: InputMode
  modelConfig: ModelConfig
  /**
   * Equals the binary's strategy id (21 §5.1).
   */
  strategyId: string
}

/**
 * `ModelConfig.runner` (12 §6.3).
 */
export interface RunnerConfig {
  maxEventsPerDrain: number
}

/**
 * `ModelConfig.execution.sellGate` (13 §7.3; realistic, M3b).
 */
export type SellGate = 'Matched' | 'Mined' | 'Confirmed'

/**
 * TS to binary (20 §6.2).
 */
export type ServeIn =
  | {
      contextId: string
      run: RunSection
      type: 'context'
    }
  | {
      job: ServeJob
      jobId: string
      type: 'job'
    }
  | {
      jobId: string
      type: 'cancel'
    }
  | {
      id: number
      type: 'ping'
    }
  | {
      type: 'drain'
    }

/**
 * An `EngineJob` whose run section is inline (`run`) or a cached context
 * (`runRef`), exactly one of the two (20 §6.2).
 */
export interface ServeJob {
  budget: JobBudget
  jobSchemaVersion: 1
  market: MarketSection
  outputs: JobOutputs
  run?: RunSection
  runRef?: string
}

/**
 * Binary to TS (20 §6.2). Serialize-only (see the module docs).
 */
export type ServeOut =
  | {
      contractSha256: string
      engineVersion: string
      jobSchemaVersions: number[]
      maxInflight: number
      perfLevels: PerfLevel[]
      pid: number
      /**
       * The process role read back after the class is set (16 §10.2).
       */
      processRole: string
      protocolVersion: 2
      qos: Qos
      stackBytes: number
      strategyId: string
      threads: number
      type: 'ready'
    }
  | {
      jobId: string
      result: EngineResult
      type: 'result'
    }
  | {
      elapsedMs: number
      eventsProcessed: number
      inCallback: InCallback | null
      jobId: string
      type: 'progress'
    }
  | {
      cacheBytes: number
      id: number
      inflight: InflightJob[]
      rssBytes: number
      type: 'pong'
    }
  | {
      reason: string
      type: 'busy'
    }
  | {
      reason: string
      type: 'idle'
    }
  | {
      completed: number
      type: 'drained'
    }
  | {
      cause: string
      class: ErrorClass
      message: string
      type: 'fatal'
    }

/**
 * Top-level `skipReason` of a market output (21 §13, §17).
 */
export type SkipReason =
  | 'no_slug'
  | 'no_resolution'
  | 'unresolved_outcome'
  | 'no_activity'
  | 'incomplete_capture'

/**
 * `marketStats.skipReason` (MySQL enum, 21 §17).
 */
export type StatsSkipReason = 'no_in_window_activity'

/**
 * `ModelConfig.execution.models.takerDelay` (13 §7.3).
 */
export type TakerDelayModel = 'on' | 'off'

export interface TokenIds {
  DOWN: string
  UP: string
}

/**
 * Parity trace level (22 §3.2, 20 §5.4).
 */
export type TraceLevel = 'decisions' | 'feeds'

/**
 * Market window in epoch ms (10 §5).
 */
export interface Window {
  endMs: number
  startMs: number
}
