/**
 * index-registry.ts — regenerate protocol/registry/INDEX.md from the
 * experiment files. Never hand-edit INDEX.md (DECISIONS D4).
 *
 * Status is derived from the last verdict block's `decision:` line; an
 * experiment with no verdicts is `registered`.
 *
 * Usage: npx tsx fable-lab/tools/index-registry.ts
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { REGISTRY_DIR, parseSpecFile } from './lib/spec.js'

const INDEX_PATH = join(REGISTRY_DIR, '..', 'INDEX.md')

function lastDecision(md: string): string {
  const decisions = [...md.matchAll(/^\s*[-*]?\s*(?:\*\*)?decision(?:\*\*)?:\s*(.+)$/gim)]
  return decisions.length ? decisions[decisions.length - 1][1].trim() : 'registered'
}

function main() {
  let files: string[] = []
  try {
    files = readdirSync(REGISTRY_DIR)
      .filter((f) => /^EXP-\d+.*\.md$/i.test(f))
      .sort()
  } catch {
    // registry dir missing — leave files empty
  }

  const lines = [
    '# Registry index',
    '',
    'Generated by `fable-lab/tools/index-registry.ts` — do not hand-edit.',
    '',
  ]
  if (files.length === 0) {
    lines.push('_No experiments registered yet._')
  } else {
    lines.push('| exp | title | mechanism | status | file |')
    lines.push('|---|---|---|---|---|')
    for (const f of files) {
      const path = join(REGISTRY_DIR, f)
      const spec = parseSpecFile(path)
      const md = readFileSync(path, 'utf8')
      lines.push(
        `| ${spec.expId ?? '?'} | ${spec.title ?? '?'} | ${spec.mechanismClass ?? '?'} | ${lastDecision(md)} | [${f}](./experiments/${f}) |`,
      )
    }
  }
  lines.push('')
  writeFileSync(INDEX_PATH, lines.join('\n'))
  console.log(`wrote ${INDEX_PATH} (${files.length} experiments)`)
}

main()
