[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2021"
version = "0.1.0"
publish = false
rust-version = "1.89"

[workspace.dependencies]
anyhow = "=1.0.98"
chrono = { version = "=0.4.45", default-features = false, features = ["std"] }
flate2 = "=1.1.2"
parquet = { version = "=56.2.0", default-features = false, features = ["snap", "flate2-rust_backened", "zstd", "lz4"] }
serde = { version = "=1.0.219", features = ["derive", "rc"] }
serde_json = { version = "=1.0.141", features = ["float_roundtrip"] }
sha2 = "=0.10.9"
pmb-core = { path = "crates/pmb-core" }
pmb-replay = { path = "crates/pmb-replay" }
pmb-sdk = { path = "crates/pmb-sdk" }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
dbg_macro = "deny"

[profile.release]
lto = "thin"
codegen-units = 1
