#!/usr/bin/env bash
# Safety-kit launcher prerequisite for the pair protocol (protocols/pair/VISION.md
# §Safety kit). Creates or refreshes an AGENT WORKTREE with:
#   - a GENERATED minimal .env: DRY_RUN=true hardcoded, whitelisted keys only —
#     never a copy of the root .env (which holds live keys)
#   - a worktree-scoped pre-commit hook (hooks/) enforcing commit scope +
#     secret scan; the agent name is pinned in git config pair.agent
#   - node_modules and data/ SYMLINKED from the main checkout (always fresh,
#     no duplicate installs/downloads). Consequence: agents must never run
#     npm install/ci — deps are the human's job in the main checkout.
#
# Usage: protocols/pair/scripts/setup-agent-worktree.sh <agent> [branch]
#   <agent>  lowercase name, e.g. fable | gpt | opus
#   [branch] base branch for the worktree (default: main)
set -euo pipefail

AGENT="${1:-}"
BRANCH="${2:-main}"

if [[ ! "$AGENT" =~ ^[a-z0-9-]+$ ]]; then
  echo "usage: $0 <agent> [branch]  (agent: lowercase [a-z0-9-])" >&2
  exit 2
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
WT="$(dirname "$ROOT")/polymarket-bot-pair-${AGENT}"
# Hooks are referenced from the MAIN checkout (this repo), not the worktree
# copy — and the hook protects protocols/pair/scripts/** from agent commits,
# so agents cannot weaken their own guardrails through the normal flow.
HOOKS_DIR="$ROOT/protocols/pair/scripts/hooks"

cd "$ROOT"
git fetch origin "$BRANCH" --quiet

# --- worktree ---------------------------------------------------------------
if [[ -d "$WT" ]]; then
  echo "[pair-setup] worktree exists: $WT (refreshing config only)"
else
  git worktree add -b "wt/pair-${AGENT}" "$WT" "origin/${BRANCH}"
  echo "[pair-setup] worktree created: $WT (branch wt/pair-${AGENT} from origin/${BRANCH})"
fi

# --- generated minimal .env (NEVER copy the root .env) -----------------------
# Whitelist: exactly what backtesting against the fleet needs — DB (results),
# Redis (queue), R2 (dataset pulls), telonex floor. Nothing that can touch
# money: no PRIVATE_KEY, no POLYMARKET_*, no CLOB_*, no relayer, no RPC.
WHITELIST=(
  DATABASE_HOST DATABASE_PORT DATABASE_USERNAME DATABASE_PASSWORD DATABASE_NAME
  REDIS_URL
  R2_ENDPOINT R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY R2_BUCKET
  TELONEX_DATASET_ELIGIBLE_FROM
)
ENV_OUT="$WT/.env"
{
  echo "# GENERATED by scripts/pair/setup-agent-worktree.sh — do not copy the root .env here."
  echo "# Agent worktrees hold NO trading keys. DRY_RUN is forced true."
  echo "DRY_RUN=true"
  for key in "${WHITELIST[@]}"; do
    line="$(grep -E "^${key}=" "$ROOT/.env" 2>/dev/null | head -1 || true)"
    [[ -n "$line" ]] && echo "$line"
  done
} > "$ENV_OUT"
chmod 600 "$ENV_OUT"
echo "[pair-setup] generated $ENV_OUT ($(grep -c '=' "$ENV_OUT") vars, DRY_RUN=true forced)"

# --- worktree-scoped hooks + agent identity ----------------------------------
git config extensions.worktreeConfig true
git -C "$WT" config --worktree core.hooksPath "$HOOKS_DIR"
git -C "$WT" config --worktree pair.agent "$AGENT"
echo "[pair-setup] pre-commit scope hook active (core.hooksPath=$HOOKS_DIR, pair.agent=$AGENT)"

# --- agent home --------------------------------------------------------------
mkdir -p "$WT/protocols/pair/models/${AGENT}"

# --- shared node_modules + data (symlinks to the main checkout) --------------
# Always-fresh deps, no duplicate installs, no duplicate parquet downloads.
for link in node_modules data; do
  if [[ -e "$WT/$link" && ! -L "$WT/$link" ]]; then
    echo "[pair-setup] ERROR: $WT/$link exists and is not a symlink — remove it and rerun" >&2
    exit 1
  fi
  ln -sfn "$ROOT/$link" "$WT/$link"
done
echo "[pair-setup] symlinked node_modules + data -> $ROOT"

echo "[pair-setup] READY: $WT"
echo "  next: launch the agent with cwd $WT/protocols/pair/models/${AGENT}"
