#!/usr/bin/env bash
# Safety-kit launcher prerequisite for the pair protocol (protocols/pair/VISION.md
# §Safety kit). Creates or refreshes an MODEL WORKTREE with:
#   - a GENERATED minimal .env: DRY_RUN=true hardcoded, whitelisted keys only —
#     never a copy of the root .env (which holds live keys)
#   - a worktree-scoped pre-commit hook (hooks/) enforcing commit scope +
#     secret scan; the model name is pinned in git config pair.model
#   - node_modules and data/ SYMLINKED from the main checkout (always fresh,
#     no duplicate installs/downloads). Consequence: models must never run
#     npm install/ci — deps are the human's job in the main checkout.
#
# Usage: protocols/pair/scripts/setup-model-worktree.sh <model> [branch] [protocol]
#   <model>    lowercase name, e.g. fable | gpt | opus
#   [branch]   base branch for the worktree (default: main)
#   [protocol] protocol directory name under protocols/ (default: pair).
#              Single-agent protocols like pair-fable get a worktree named
#              after the protocol and write scopes rooted at their own dir.
set -euo pipefail

MODEL="${1:-}"
BRANCH="${2:-main}"
PROTOCOL="${3:-pair}"

if [[ ! "$MODEL" =~ ^[a-z0-9-]+$ || ! "$PROTOCOL" =~ ^[a-z0-9-]+$ ]]; then
  echo "usage: $0 <model> [branch] [protocol]  (model/protocol: lowercase [a-z0-9-])" >&2
  exit 2
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
if [[ ! -d "$ROOT/protocols/$PROTOCOL" ]]; then
  echo "[pair-setup] ERROR: protocols/$PROTOCOL does not exist in $ROOT" >&2
  exit 2
fi
if [[ "$PROTOCOL" == "pair" ]]; then
  WT="$(dirname "$ROOT")/polymarket-bot-pair-${MODEL}"
else
  WT="$(dirname "$ROOT")/polymarket-bot-${PROTOCOL}"
fi
# Hooks are referenced from the MAIN checkout (this repo), not the worktree
# copy — and the hook protects protocols/pair/scripts/** from model commits,
# so models cannot weaken their own guardrails through the normal flow.
HOOKS_DIR="$ROOT/protocols/pair/scripts/hooks"

cd "$ROOT"
git fetch origin "$BRANCH" --quiet

# --- worktree ---------------------------------------------------------------
if [[ "$PROTOCOL" == "pair" ]]; then
  WT_BRANCH="wt/pair-${MODEL}"
else
  WT_BRANCH="wt/${PROTOCOL}"
fi
if [[ -d "$WT" ]]; then
  echo "[pair-setup] worktree exists: $WT (refreshing config only)"
else
  git worktree add -b "$WT_BRANCH" "$WT" "origin/${BRANCH}"
  echo "[pair-setup] worktree created: $WT (branch $WT_BRANCH from origin/${BRANCH})"
fi

# --- generated minimal .env (NEVER copy the root .env) -----------------------
# Whitelist: exactly what backtesting against the fleet needs — DB (results),
# Redis (queue), R2 (dataset pulls), telonex floor. Nothing that can touch
# money: no PRIVATE_KEY, no POLYMARKET_*, no CLOB_*, no relayer, no RPC.
WHITELIST=(
  DATABASE_HOST DATABASE_PORT DATABASE_USERNAME DATABASE_PASSWORD DATABASE_NAME
  REDIS_URL
  R2_ENDPOINT R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY R2_BUCKET
  TELONEX_DATASET_ELIGIBLE_FROM
)
ENV_OUT="$WT/.env"
{
  echo "# GENERATED by scripts/pair/setup-model-worktree.sh — do not copy the root .env here."
  echo "# Model worktrees hold NO trading keys. DRY_RUN is forced true."
  echo "DRY_RUN=true"
  for key in "${WHITELIST[@]}"; do
    line="$(grep -E "^${key}=" "$ROOT/.env" 2>/dev/null | head -1 || true)"
    [[ -n "$line" ]] && echo "$line"
  done
} > "$ENV_OUT"
chmod 600 "$ENV_OUT"
echo "[pair-setup] generated $ENV_OUT ($(grep -c '=' "$ENV_OUT") vars, DRY_RUN=true forced)"

# --- worktree-scoped hooks + model identity ----------------------------------
git config extensions.worktreeConfig true
git -C "$WT" config --worktree core.hooksPath "$HOOKS_DIR"
git -C "$WT" config --worktree pair.model "$MODEL"
git -C "$WT" config --worktree pair.protocolDir "protocols/${PROTOCOL}"
echo "[pair-setup] pre-commit scope hook active (core.hooksPath=$HOOKS_DIR, pair.model=$MODEL, pair.protocolDir=protocols/$PROTOCOL)"

# --- agent home --------------------------------------------------------------
if [[ "$PROTOCOL" == "pair" ]]; then
  mkdir -p "$WT/protocols/pair/models/${MODEL}"
else
  mkdir -p "$WT/protocols/${PROTOCOL}/state" "$WT/protocols/${PROTOCOL}/memory" "$WT/protocols/${PROTOCOL}/tools"
fi

# --- shared node_modules + data (symlinks to the main checkout) --------------
# Always-fresh deps, no duplicate installs, no duplicate parquet downloads.
for link in node_modules data; do
  if [[ -e "$WT/$link" && ! -L "$WT/$link" ]]; then
    echo "[pair-setup] ERROR: $WT/$link exists and is not a symlink — remove it and rerun" >&2
    exit 1
  fi
  ln -sfn "$ROOT/$link" "$WT/$link"
done
echo "[pair-setup] symlinked node_modules + data -> $ROOT"

echo "[pair-setup] READY: $WT"
if [[ "$PROTOCOL" == "pair" ]]; then
  echo "  next: launch the model with cwd $WT/protocols/pair/models/${MODEL}"
else
  echo "  next: create the Global Runtime loop with --workspace $WT (see protocols/${PROTOCOL}/README.md)"
fi
