#!/usr/bin/env bash
# Safety-kit launcher prerequisite for the pair protocol (protocols/pair/VISION.md
# §Safety kit). Creates or refreshes an AGENT WORKTREE with:
#   - a GENERATED minimal .env: DRY_RUN=true hardcoded, whitelisted keys only —
#     never a copy of the root .env (which holds live keys)
#   - a worktree-scoped pre-commit hook (scripts/pair/hooks) enforcing commit
#     scope + secret scan; the agent name is pinned in git config pair.agent
#   - its own npm ci (no node_modules symlink shared with the live checkout)
#
# Usage: scripts/pair/setup-agent-worktree.sh <agent> [branch] [--no-install]
#   <agent>  lowercase name, e.g. fable | gpt | opus
#   [branch] base branch for the worktree (default: main)
set -euo pipefail

AGENT="${1:-}"
BRANCH="${2:-main}"
NO_INSTALL="${3:-}"
[[ "$BRANCH" == "--no-install" ]] && { NO_INSTALL="--no-install"; BRANCH="main"; }

if [[ ! "$AGENT" =~ ^[a-z0-9-]+$ ]]; then
  echo "usage: $0 <agent> [branch] [--no-install]  (agent: lowercase [a-z0-9-])" >&2
  exit 2
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
WT="$(dirname "$ROOT")/polymarket-bot-pair-${AGENT}"
HOOKS_DIR="$ROOT/scripts/pair/hooks"

cd "$ROOT"
git fetch origin "$BRANCH" --quiet

# --- worktree ---------------------------------------------------------------
if [[ -d "$WT" ]]; then
  echo "[pair-setup] worktree exists: $WT (refreshing config only)"
else
  git worktree add -b "wt/pair-${AGENT}" "$WT" "origin/${BRANCH}"
  echo "[pair-setup] worktree created: $WT (branch wt/pair-${AGENT} from origin/${BRANCH})"
fi

# --- generated minimal .env (NEVER copy the root .env) -----------------------
# Whitelist: exactly what backtesting against the fleet needs — DB (results),
# Redis (queue), R2 (dataset pulls), telonex floor. Nothing that can touch
# money: no PRIVATE_KEY, no POLYMARKET_*, no CLOB_*, no relayer, no RPC.
WHITELIST=(
  DATABASE_HOST DATABASE_PORT DATABASE_USERNAME DATABASE_PASSWORD DATABASE_NAME
  REDIS_URL
  R2_ENDPOINT R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY R2_BUCKET
  TELONEX_DATASET_ELIGIBLE_FROM
)
ENV_OUT="$WT/.env"
{
  echo "# GENERATED by scripts/pair/setup-agent-worktree.sh — do not copy the root .env here."
  echo "# Agent worktrees hold NO trading keys. DRY_RUN is forced true."
  echo "DRY_RUN=true"
  for key in "${WHITELIST[@]}"; do
    line="$(grep -E "^${key}=" "$ROOT/.env" 2>/dev/null | head -1 || true)"
    [[ -n "$line" ]] && echo "$line"
  done
} > "$ENV_OUT"
chmod 600 "$ENV_OUT"
echo "[pair-setup] generated $ENV_OUT ($(grep -c '=' "$ENV_OUT") vars, DRY_RUN=true forced)"

# --- worktree-scoped hooks + agent identity ----------------------------------
git config extensions.worktreeConfig true
git -C "$WT" config --worktree core.hooksPath "$HOOKS_DIR"
git -C "$WT" config --worktree pair.agent "$AGENT"
echo "[pair-setup] pre-commit scope hook active (core.hooksPath=$HOOKS_DIR, pair.agent=$AGENT)"

# --- agent home --------------------------------------------------------------
mkdir -p "$WT/protocols/pair/agents/${AGENT}"

# --- own dependencies (no symlink to the live checkout) ----------------------
if [[ "$NO_INSTALL" == "--no-install" ]]; then
  echo "[pair-setup] skipping npm ci (--no-install)"
elif [[ -L "$WT/node_modules" ]]; then
  echo "[pair-setup] ERROR: node_modules is a symlink — remove it and rerun" >&2
  exit 1
else
  (cd "$WT" && npm ci --no-audit --no-fund)
  echo "[pair-setup] npm ci done"
fi

echo "[pair-setup] READY: $WT"
echo "  next: launch the agent with cwd $WT/protocols/pair/agents/${AGENT}"
